webapi:
  build: hydroid/api
  ports:
   - "9090:9090"
  links:
    - db
    - solr
    - jena
    - stanbol
db:
  build: hydroid/postgres
  environment:
    POSTGRES_USER: hydroid
    POSTGRES_PASSWORD: postgres
solr:
  build: hydroid/solr
  ports:
   - "8983:8983"
jena:
  build: hydroid/jena
  ports:
   - "3030:3030"
stanbol:
  build: hydroid/stanbol
  ports:
   - "8080:8080"